### ISSUE TITLE
Collect transaction jumps

### ISSUE THREAD

**Issue by 4l0n50** [0xPolygonZero/erigon#1]
# Rationale

In order to improve the performance of jumpdest analysis during plonky2 evm witness generation, it is necessary to provide the list of all jump destinations with their respective contexts.

# Implementation

It should involve storing the top of the stack when the program counter points to a JUMP, or storing the element below the top of the stack if the top of the stack is not equal to zero in a JUMPI, along with the current context.

**Comment by Nashtare** [comment]
Hey @cffls! Friendly ping on this issue, do you think this is something we could see coming in the coming weeks? It'd be really nice if the prover didn't have to do all the JD analysis work on its own 🙂

**Comment by cffls** [comment]
Hey @4l0n50 @Nashtare , this is something not traced in opcode tracer? If we want to include this in zero tracer, the trace output format might need to change quite a bit.

**Comment by Nashtare** [comment]
Moved to https://github.com/0xPolygonZero/zk_evm/issues/290.
